etl_robot_app/urls.py
from django.conf.urls import url,include
from .import views
from django.contrib.auth import views as auth_views

app_name='etl_robot_app'
urlpatterns = [
url(r'^login/$', auth_views.login,{'template_name': 'login.html'}, name='login'),
url(r'^logout/$', auth_views.logout, {'template_name': 'login.html'}, name='logout'),
url(r'register', views.RegistrationView.as_view(), name='register'),
url(r'^success', views.RegistrationSuccessView.as_view(), name='registersuccess'),
url(r'dashboard', views.DashboardView.as_view(), name='dashboard'),
url(r'rows/today', views.RowsSyncedToday.as_view(), name='today_row_count'),
url(r'rows/period', views.RowsSyncedPeriod.as_view(), name='period_row_count'),
url(r'notification/count', views.NotificationCount.as_view(), name='notification_count'),
url(r'integrationactive/count', views.ActiveIntegrationCount.as_view(), name='active_integrations'),
url(r'daily/volume', views.DailyVolume.as_view(), name='get_daily_volume'),
url(r'integration/donut', views.IntegrationDonutView.as_view(), name='get_integration_donut'),
url(r'integration/summary', views.IntegrationSummary.as_view(), name='get_integration_summary'),
url(r'dataintegration', views.IntegrationView.as_view(), name='integrations'),
url(r'facebookinsightintegration', views.FacebookInsightsIntegrationView.as_view(), name='fbinsightintegrations'),
url(r'facebookadsintegration', views.FacebookAdsIntegrationView.as_view(), name='facebookadsintegration'),
url(r'analyticsintegration', views.GoogleAnalyticsIntegrationView.as_view(), name='analyticsintegration'),
url(r'pinterestintegration', views.PinterstIntegrationView.as_view(), name='pinterestintegration'),
url(r'five9tintegration', views.Five9IntegrationView.as_view(), name='five9tintegration'),
url(r'facebook/ads', views.FacebookAdAuthView.as_view(), name='facebookadsrcintegration'),
url(r'pages/insights', views.FacebookPageAuthView.as_view(), name='facebookinsightsrcintegration'),
url(r'google/analytics', views.GoogleAuthView.as_view(), name='analyticssrcintegration'),
url(r'pinterest/boards', views.PinterestAuthView.as_view(), name='pinterestsrcintegration'),
url(r'fiveNine', views.Five9AuthView.as_view(), name='five9srctintegration'),
url(r'five9details', views.FiveNineDetailView.as_view(), name='fiveNinedetails'),
url(r'fbaddetails', views.FBAdDetialsView.as_view(), name='fbaddetails'),
url(r'fbinsightdetails', views.FBInsightDetailView.as_view(), name='fbinsightdetails'),
url(r'googleanalyticsdetails', views.GoogleAnalyticsDetailView.as_view(), name='googleanalyticsdetails'),
url(r'pinterestdetails', views.PinterestDetailView.as_view(), name='pinterestdetails'),
url(r'datasourceset', views.DataSourceSetView.as_view(), name='get_data_source_set'),
url(r'datatarget', views.DataTargetView.as_view(), name='get_data_target'),
url(r'mysqltarget', views.MysqlTargetView.as_view(), name='mysqltarget'),
url(r'bigquerytarget', views.GoogleBigQueryAuthView.as_view(), name='bigquerytarget'),
url(r'googlebigquerydetails', views.GoogleBigQueryDetailView.as_view(), name='googlebigquerydetails'),
url(r'integrationsuccess', views.IntegrationSuccessView.as_view(), name='integration_success'),
url(r'testdbconnection', views.TestDbConnectionView.as_view(), name='testdbconnection'),
#
]

etlrobot/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('etl_robot_app.urls')),
url(r'^password_reset/$', auth_views.password_reset,{'template_name':'passwordreset/password_reset_form.html', 'html_email_template_name':'passwordreset/password_reset_email.html',
                   'subject_template_name':'passwordreset/password_reset_subject.txt'}, name='password_reset'),

url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm,{'template_name':'passwordreset/password_reset_confirm.html'}, name='password_reset_confirm'),

url(r'^password_reset/done/$', auth_views.password_reset_done,{'template_name':'passwordreset/password_reset_done.html'}, name='password_reset_done'),

url(r'^reset/done/$', auth_views.password_reset_complete,{'template_name':'passwordreset/password_reset_complete.html'}, name='password_reset_complete'),
url(r'^auth/', include('social_django.urls', namespace='social')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

etl_robot_app/views.py
from django.shortcuts import render,redirect
from django.urls import reverse
from django.views import generic
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from .forms import RegistrationForm,FiveNineForm,MysqlForm
from .models import User, Account, VBillingPeriod, VCalendarPeriod,Target
from .email import SendEmail
from django.http import HttpResponse,HttpResponseRedirect
from .dashboardmixin import DashboardMixin
from .integrationmixin import IntegrationMixin
import json
from etlrobot import settings
from django.contrib.sites.models import Site
import requests
import urllib
from facebookads.api import FacebookAdsApi
from facebookads.exceptions import FacebookRequestError
from facebookads.adobjects.adaccountuser import AdAccountUser
from facebookads.adobjects.adaccount import AdAccount
from facebookads.adobjects.adset import AdSet
import httplib2
from oauth2client.client import OAuth2Credentials
from googleapiclient.discovery import build
import sys
# Create your views here.

class RegistrationView(generic.View):
    def post(self,request):
        form =RegistrationForm(request.POST)
        if form.is_valid():
            account = Account(company_name=form.cleaned_data.get('company'))
            account.save()
            account.refresh_from_db()
            if account.company_name:
                create_user = User.objects.get_or_create(account_id=account,email=form.cleaned_data.get('email'),first_name=form.cleaned_data.get('first_name'),last_name =form.cleaned_data.get('last_name'))
                if create_user:
                    email_status = SendEmail.send_mail_register(create_user)
                    if(email_status):
                        return HttpResponseRedirect(reverse('etl_robot_app:registersuccess'))

            else:
                return render(request, 'register.html', {'form': form,'error_message':'Some Error Occured'})

        else:
            return render(request, 'register.html', {'form': form})

    def get(self, request):
        form = RegistrationForm()
        return render(request, 'register.html', {'form': form})

class RegistrationSuccessView(generic.TemplateView):
    #template_name = 'emailregtemplate.html'
    template_name = 'register_done.html'

@method_decorator(login_required, name='dispatch')
class DashboardView(generic.TemplateView):
    template_name = 'dashboard/dashboard.html'

    def get(self,request):
          billing_period = VBillingPeriod.objects.filter(account_id=request.user.account_id.id)
          if not billing_period:
              billing_period = VCalendarPeriod.objects.all()
          return render(request,'dashboard/dashboard.html',{'billing_period':billing_period })

@method_decorator(login_required, name='dispatch')
class RowsSyncedPeriod(generic.View,DashboardMixin):
    def post(self,request):
        result = {}
        if request.POST['period_end_utc'] and request.POST['period_start_utc']:
            data =self.get_dashboard_summary(request.user.account_id,request.POST['period_start_utc'],request.POST['period_end_utc'],False)
            result['status'] = True
            result['data'] = data
        else:
            result['status'] = False
            result['message']='Kindly Select a valid Date Range'
        return HttpResponse(json.dumps(result), content_type="application/json")


@method_decorator(login_required, name='dispatch')
class RowsSyncedToday(generic.View,DashboardMixin):
    def post(self,request):
        result = {}
        data = self.get_dashboard_summary(request.user.account_id)
        result['status'] = True
        result['data'] = data

        return HttpResponse(json.dumps(result), content_type="application/json")

@method_decorator(login_required, name='dispatch')
class ActiveIntegrationCount(generic.View,DashboardMixin):
    def post(self,request):
        result = {}
        data = self.get_dashboard_integration_count(request.user.account_id)
        result['status'] = True
        result['data'] = data

        return HttpResponse(json.dumps(result), content_type="application/json")

@method_decorator(login_required,name='dispatch')
class NotificationCount(generic.View,DashboardMixin):
    def post(self,request):
        result={}
        data = self.get_notification_count(request.user.account_id)
        result['status']=True
        result['data']=data
        return HttpResponse(json.dumps(result),content_type="application/json")

@method_decorator(login_required,name='dispatch')
class DailyVolume(generic.View,DashboardMixin):
    def post(self,request):
        result = {}
        if request.POST['period_end_utc'] and request.POST['period_start_utc']:
            data =self.get_dashboard_summary(request.user.account_id,request.POST['period_start_utc'],request.POST['period_end_utc'],flag=True)
            result['status'] = True
            result['data'] =  data

        else:
            result['status'] = False
            result['message']='Kindly Select a valid Date Range'
        return HttpResponse(json.dumps(result), content_type="application/json")

@method_decorator(login_required,name='dispatch')
class IntegrationDonutView(generic.View,DashboardMixin):
    def post(self,request):
        result = {}
        if request.POST['period_end_utc'] and request.POST['period_start_utc']:
            data = self.get_dashboard_summary(request.user.account_id, request.POST['period_start_utc'],request.POST['period_end_utc'], flag='donut')
            result['status'] = True
            result['data'] = data

        else:
            result['status'] = False
            result['message'] = 'Kindly Select a valid Date Range'
        return HttpResponse(json.dumps(result), content_type="application/json")

@method_decorator(login_required,name='dispatch')
class IntegrationSummary(generic.View,DashboardMixin):
    def post(self,request):
        result ={}
        if request.POST['period_end_utc'] and request.POST['period_start_utc']:
            data = self.get_integration_summary(request.user.account_id,request.POST['period_start_utc'],request.POST['period_end_utc'])
            result['status'] = True
            result['data'] = data
        else:
            result['status'] = False
            result['message'] = 'Kindly Select a valid Date Range'
        return HttpResponse(json.dumps(result), content_type="application/json")

@method_decorator(login_required,name='dispatch')
class IntegrationView(generic.View,IntegrationMixin):

    def get(self,request):
        category =self.get_integration_category()
        source =self.get_integration_source()
        src_category =self.get_category_integration_src()
        target=self.get_target()
        return render(request,'integration/integration.html',{'category':category,'source':source,'src_catgory':src_category,'target':target})


@method_decorator(login_required,name='dispatch')
class FacebookAdsIntegrationView(generic.View,IntegrationMixin):

    def get(self,request):
        frequency = self.get_frequency()
        source = self.get_integration_source(settings.FACEBOOK_ADS)
        time_zone = ""
        additional_option = self.get_additional_option(settings.FACEBOOK_ADS)
        if additional_option:
            time_zone =self.get_timezone_additonal_details()
        return render(request,'integration/integration-page.html',{'source':source,'frequency':frequency,'additional_option':additional_option,'time_zone':time_zone})


@method_decorator(login_required,name='dispatch')
class FacebookInsightsIntegrationView(generic.View,IntegrationMixin):

    def get(self,request):
        frequency = self.get_frequency()
        source = self.get_integration_source(settings.FACEBOOK_INSIGHT)
        time_zone = ""
        additional_option = self.get_additional_option(settings.FACEBOOK_INSIGHT)
        if additional_option:
            time_zone = self.get_timezone_additonal_details()
        return render(request, 'integration/integration-page.html',{'source': source, 'frequency': frequency, 'additional_option': additional_option,'time_zone': time_zone})

@method_decorator(login_required,name='dispatch')
class PinterstIntegrationView(generic.View,IntegrationMixin):

    def get(self,request):
        frequency = self.get_frequency()
        source = self.get_integration_source(settings.PINTEREST)
        time_zone = ""
        additional_option = self.get_additional_option(settings.PINTEREST)
        if additional_option:
            time_zone = self.get_timezone_additonal_details()
        return render(request, 'integration/integration-page.html',{'source': source, 'frequency': frequency, 'additional_option': additional_option,'time_zone': time_zone})

@method_decorator(login_required,name='dispatch')
class GoogleAnalyticsIntegrationView(generic.View,IntegrationMixin):

    def get(self,request):
        frequency = self.get_frequency()
        source = self.get_integration_source(settings.GOOGLE_ANALYTICS)
        time_zone = ""
        additional_option = self.get_additional_option(settings.GOOGLE_ANALYTICS)
        if additional_option:
            time_zone = self.get_timezone_additonal_details()
        return render(request, 'integration/integration-page.html',                     {'source': source, 'frequency': frequency, 'additional_option': additional_option,'time_zone': time_zone})

@method_decorator(login_required,name='dispatch')
class Five9IntegrationView(generic.View,IntegrationMixin):

    def get(self,request):
        frequency = self.get_frequency()
        source = self.get_integration_source(settings.FIVE9)
        time_zone = ""
        additional_option = self.get_additional_option(settings.FIVE9)
        if additional_option:
            time_zone = self.get_timezone_additonal_details()

etl_robot_app/templates/passwordreset/password_reset_complete.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'assets/css/login.css' %}">
 <div class="loginCon mesg">
      <div class="mesgInner">


        <div class="successMod">
          <div class="successhead">
            <img class="logoImg" src="{% static 'assets/img/logo-ETLRobot.png' %}"><!-- logo-etl.svg -->
          </div>

          <div class="succesBody">

            <i class="anim">
             <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 130.2 130.2"> <circle class="path circle" fill="none" stroke="#08ac67" stroke-width="6" stroke-miterlimit="10" cx="65.1" cy="65.1" r="62.1"></circle> <polyline class="path check" fill="none" stroke="#08ac67" stroke-width="6" stroke-linecap="round" stroke-miterlimit="10" points="100.2,40.2 51.5,88.8 29.8,67.5 "></polyline> </svg>
            </i>

            <h2>Password Changed successfully</h2>

            <p>
              Your password has been set
            </p>

            <p>
              Didn't reveive an email from us? Contact <span class="emailSpan">steve@etlrobot.com</span>
            </p>

            <br>
            <a class="link-d" href="{% url 'etl_robot_app:login' %}">Login Now</a>

          </div>
        </div>


      </div>

      {% block footer %}<p>Copyright © 2018 <a class="link-d" href="javascript: void(0)">ETL Robot.</a> All rights reserved.</p>{% endblock %}
    </div>

{% endblock %}

etl_robot_app/templates/passwordreset/password_reset_confirm.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Change password | etlrobotsaas{% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static 'assets/css/login.css' %}">

<div class="loginCon">
      <div class="loginCon_inner">


        <div class="loginMod">
          <div class="loginMod_h">
            <img src="{% static 'assets/img/logo-ETLRobot.png' %}">
          </div>
          <div class="container-fluid">

              {% if validlink %}
              <span> {{ form.non_field_errors }}</span>
            <form  autocomplete="off" method="POST">
              {% csrf_token %}
                <div class="form-group hasFloatingSpan">
                <div class="input-group">
                  <span class="input-group-addon"><i class="fa fa-lock"></i></span>
                  <input id="password" type="password" class="form-control" name="new_password1" value="" onkeyup="this.setAttribute('value', this.value);" onblur="this.setAttribute('value', this.value);" autocomplete="off">
                  <span class="floatingSpan">Password</span>
                     <span style="color:red"> {{ form.new_password1.errors }}</span>
                  </div>
              </div>
                 <div class="form-group hasFloatingSpan">
                <div class="input-group">
                  <span class="input-group-addon"><i class="fa fa-lock"></i></span>
                  <input id="confirm-password" type="password" class="form-control" name="new_password2" value="" onkeyup="this.setAttribute('value', this.value);" onblur="this.setAttribute('value', this.value);" autocomplete="off">
                  <span class="floatingSpan">Confirm Password</span>
                    <span style="color:red"> {{ form.new_password2.errors }}</span>
                  </div>
              </div>
              <div class="form-group text-center btn-login-con">
                <button type="submit" class="btn btn-login btn-success">Change Password</button>
              </div>
            </form>
              {% else %}
    <p>
      The password reset link was invalid, possibly because it has already been used.
      Please request a new password reset.
    </p>
  {% endif %}
          </div>
        </div>


      </div>

      {% block footer %}
        <p>Copyright © 2018 <a class="link-d" href="javascript: void(0)">ETL Robot.</a> All rights reserved.</p>
      {% endblock %}
    </div>
{% endblock %}

etl_robot_app/templates/passwordreset/password_reset_done.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'assets/css/login.css' %}">
 <div class="loginCon mesg">
      <div class="mesgInner">


        <div class="successMod">
          <div class="successhead">
            <img class="logoImg" src="{% static 'assets/img/logo-ETLRobot.png' %}"><!-- logo-etl.svg -->
          </div>

          <div class="succesBody">

            <i class="anim">
             <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 130.2 130.2"> <circle class="path circle" fill="none" stroke="#08ac67" stroke-width="6" stroke-miterlimit="10" cx="65.1" cy="65.1" r="62.1"></circle> <polyline class="path check" fill="none" stroke="#08ac67" stroke-width="6" stroke-linecap="round" stroke-miterlimit="10" points="100.2,40.2 51.5,88.8 29.8,67.5 "></polyline> </svg>
            </i>

            <h2>Password Reset Link Send Successfully</h2>

            <h3><i class="far fa-envelope-open"></i> Reset Your Password</h3>

            <p>
               We've emailed you instructions for setting your password, if an account exists with the email you entered.
    You should receive them shortly.
            </p>

            <p>
               If you don't receive an email, please make sure you've entered the address you registered with,
    and check your spam folder.
              Didn't reveive an email from us? Contact <span class="emailSpan">steve@etlrobot.com</span>
            </p>

            <br>
            <a class="link-d" href="javascript: void(0);">Get back to home page</a>

          </div>
        </div>


      </div>

      {% block footer %}<p>Copyright © 2018 <a class="link-d" href="javascript: void(0)">ETL Robot.</a> All rights reserved.</p>{% endblock %}
    </div>

{% endblock %}

etl_robot_app/templates/passwordreset/password_reset_email.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <title>ETL Robot</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <style>

  .container {
    margin: 0 auto;
    width: 640px;
  }
  p {
    word-break: break-all;
  }

  @media (max-width: 640px) {
  .container{width:90% !important; padding: 0 5%;}
  .white-box {padding: 20px !important;}
  }

  </style>

</head>

  <body style="background:#f7f7f7; margin:0;">
{% autoescape off %}
<div class="container">
  <table style="margin:auto;">

    <!--logo-space-->
    <tr style="text-align:center; margin: 30px auto; text-align: center;  width: 100%;">
        <td style="padding: 22px 0;text-align: center;">
          <a href=""><img src="http://sperico.com:8095/media/images/logo-etl.svg" alt=""  style="height: 46px; max-width:100%;"/></a>
        </td>
    </tr>

    <!--text-content-->
    <tr class="" style=" width:100%; max-width:50px; border:1px solid #c6dbe9;  background:#fff; -webkit-box-shadow: 0px 0px 5px #c0c8ca;-moz-box-shadow: 0px 0px 5px #c0c8ca;box-shadow: 0px 0px 5px #c0c8ca;">
        <td class="white-box" style="padding:50px;">

          <p style="color:#707070; font:16px/26px arial; text-align:justify; word-break: break-all;">
          Dear {{user.first_name}},<br /><br />
          We received a request to change the password for your ETLrobot account. If you did not make this request, just ignore this email. Otherwise, please click the button below to reset your password
          </p>

          <!--verify link-->
          <p style="text-align:center; word-break: break-all;"> <a href="{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}
" style="margin:40px auto; text-decoration:none; font:600 16px/26px arial;color: #08ac67; border: 2px solid #08ac67; display:inline-block; padding:10px 30px; -webkit-border-radius: 5px;-moz-border-radius: 5px;border-radius: 5px;"> Reset Password</a> </p>

          <p style="color:#707070; font:16px/26px arial; word-break: break-all;">
            You can also copy and paste below link to your browser if the above button does not works :</p>

            <p>
              <a href="{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}
" style="color: #2196F3; display:inline-block; margin:25px 0; font:15px/22px arial; background:#f7f7f7; padding:10px; -webkit-border-radius: 5px;-moz-border-radius: 5px;border-radius: 5px;">{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}
</a>
            </p>

            <p style="color:#707070; font:16px/26px arial; word-break: break-all;">
            Thanks for joining ETL Robot! You will enjoy working with us.<br /><br />

            Sincerely,<br />
            <span style="color: #08ac67; font:600 20px/26px arial;" >Team ETL Robot</span><br />
            <span style="font:600 16px/26px arial;" >www.etlrobot.com</span>
            </p>
          </td>
          <!--text-content ends here-->
        </tr>

        <tr>
          <td>
          <!--copyright-->
          <p style=" color: #777; font: 15px/25px arial;text-align: center;">
            © 2017 ETLrobot, LLC. Draper UT 84020
          </p>

          <p style="text-align: center; height: 25px; width: 100%; max-width: 350px; margin: 0px auto 50px;">
              <label style="text-align: left; background-image: url('http://sperico.com:8095/media/images/phone-icon.svg'); background-repeat: no-repeat; float: left; padding: 0px 15px 0px 23px; color: rgb(73, 73, 73); font: 14px/15px arial; margin: 0px 10px 0px 0px;"> + (0471) 4013112
              </label>

             <label style="text-align: left; background-repeat: no-repeat; background-image: url('http://sperico.com:8095/media/images/mail-icon.svg'); color: rgb(73, 73, 73); font: 14px/15px arial; float: right; margin: 0px 0px 0px 10px; padding: 0px 0px 0px 30px;"> steve@etlrobot.com
              </label>
          </p>
          </td>
        </tr>
      </table>
    </div>
  {% endautoescape %}
  </body>
</html>

etl_robot_app/templates/passwordreset/password_reset_email_cpy.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <title>ETL Robot</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <style>

  .container {
    margin: 0 auto;
    width: 640px;
  }
  p {
    word-break: break-all;
  }

  @media (max-width: 640px) {
  .container{width:90% !important; padding: 0 5%;}
  .white-box {padding: 20px !important;}
  }

  </style>

</head>

  <body style="background:#f7f7f7; margin:0;">
{% autoescape off %}
<div class="container">
  <table style="margin:auto;">

    <!--logo-space-->
    <tr style="text-align:center; margin: 30px auto; text-align: center;  width: 100%;">
        <td style="padding: 22px 0;text-align: center;">
          <a href=""><img src="{% static 'images/logo-etl.svg' %}" alt=""  style="height: 46px; max-width:100%;"/></a>
        </td>
    </tr>

    <!--text-content-->
    <tr class="" style=" width:100%; max-width:50px; border:1px solid #c6dbe9;  background:#fff; -webkit-box-shadow: 0px 0px 5px #c0c8ca;-moz-box-shadow: 0px 0px 5px #c0c8ca;box-shadow: 0px 0px 5px #c0c8ca;">
        <td class="white-box" style="padding:50px;">

          <p style="color:#707070; font:16px/26px arial; text-align:justify; word-break: break-all;">
          Dear {{user.first_name}},<br /><br />
          We received a request to change the password for your ETLrobot account. If you did not make this request, just ignore this email. Otherwise, please click the button below to reset your password
          </p>

          <!--verify link-->
          <p style="text-align:center; word-break: break-all;"> <a href="{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}
" style="margin:40px auto; text-decoration:none; font:600 16px/26px arial;color: #08ac67; border: 2px solid #08ac67; display:inline-block; padding:10px 30px; -webkit-border-radius: 5px;-moz-border-radius: 5px;border-radius: 5px;"> Reset Password</a> </p>

          <p style="color:#707070; font:16px/26px arial; word-break: break-all;">
            You can also copy and paste below link to your browser if the above button does not works :</p>

            <p>
              <a href="{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}
" style="color: #2196F3; display:inline-block; margin:25px 0; font:15px/22px arial; background:#f7f7f7; padding:10px; -webkit-border-radius: 5px;-moz-border-radius: 5px;border-radius: 5px;">{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}
</a>
            </p>

            <p style="color:#707070; font:16px/26px arial; word-break: break-all;">
            Thanks for joining ETL Robot! You will enjoy working with us.<br /><br />

            Sincerely,<br />
            <span style="color: #08ac67; font:600 20px/26px arial;" >Team ETL Robot</span><br />
            <span style="font:600 16px/26px arial;" >www.etlrobot.com</span>
            </p>
          </td>
          <!--text-content ends here-->
        </tr>

        <tr>
          <td>
          <!--copyright-->
          <p style=" color: #777; font: 15px/25px arial;text-align: center;">
            © 2017 ETLrobot, LLC. Draper UT 84020
          </p>

          <p style="text-align: center; height: 25px; width: 100%; max-width: 350px; margin: 0px auto 50px;">
              <!--<label style="text-align: left; background-image: url('{% static "images/phone-icon.svg" %}'); background-repeat: no-repeat; float: left; padding: 0px 15px 0px 23px; color: rgb(73, 73, 73); font: 14px/15px arial; margin: 0px 10px 0px 0px;"> + (0471) 4013112"-->
              <!--</label>-->

              <label style="text-align: left; background-repeat: no-repeat; background-image: url('{% static "images/mail-icon.svg" %}'); color: rgb(73, 73, 73); font: 14px/15px arial; float: right; margin: 0px 0px 0px 10px; padding: 0px 0px 0px 30px;"> steve@etlrobot.com"
              </label>
          </p>
          </td>
        </tr>
      </table>
    </div>
  {% endautoescape %}
  </body>
</html>

etl_robot_app/templates/passwordreset/password_reset_form.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Forget password | etlrobotsaas{% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static 'assets/css/login.css' %}">

<div class="loginCon">
      <div class="loginCon_inner">


        <div class="loginMod">
          <div class="loginMod_h">
            <img src="{% static 'assets/img/logo-ETLRobot.png' %}">
          </div>
          <div class="container-fluid">
              <span> {{ form.non_field_errors }}</span>
            <form  autocomplete="off" method="POST">
              {% csrf_token %}
              <div class="form-group hasFloatingSpan">
                <div class="input-group">
                  <span class="input-group-addon"><i class="fa fa-envelope"></i></span>
                  <input id="email" type="text" class="form-control" name="email" value="" onkeyup="this.setAttribute('value', this.value);" onblur="this.setAttribute('value', this.value);" autocomplete="off">
                  <span class="floatingSpan">Email</span>
                  </div>
              </div>
              <div class="form-group text-center btn-login-con">
                <button type="submit" class="btn btn-login btn-success">Reset Password</button>
              </div>
            </form>
          </div>
          <p class="loginMod_f">Back to <a class="link-d" href="{% url 'etl_robot_app:login' %}">Sign In</a></p>
        </div>


      </div>

      {% block footer %}
        <p>Copyright © 2018 <a class="link-d" href="javascript: void(0)">ETL Robot.</a> All rights reserved.</p>
      {% endblock %}
    </div>
{% endblock %}