etl_robot_app/urls.py
from django.conf.urls import url,include
from .import views
from django.contrib.auth import views as auth_views

app_name='etl_robot_app'
urlpatterns = [
url(r'^login/$', auth_views.login,{'template_name': 'login.html'}, name='login'),
url(r'^logout/$', auth_views.logout, {'template_name': 'login.html'}, name='logout'),
url(r'register', views.RegistrationView.as_view(), name='register'),
url(r'^success', views.RegistrationSuccessView.as_view(), name='registersuccess'),
url(r'dashboard', views.DashboardView.as_view(), name='dashboard'),
url(r'rows/today', views.RowsSyncedToday.as_view(), name='today_row_count'),
url(r'rows/period', views.RowsSyncedPeriod.as_view(), name='period_row_count'),
url(r'notification/count', views.NotificationCount.as_view(), name='notification_count'),
url(r'integrationactive/count', views.ActiveIntegrationCount.as_view(), name='active_integrations'),
url(r'daily/volume', views.DailyVolume.as_view(), name='get_daily_volume'),
url(r'integration/donut', views.IntegrationDonutView.as_view(), name='get_integration_donut'),
url(r'integration/summary', views.IntegrationSummary.as_view(), name='get_integration_summary'),
url(r'dataintegration', views.IntegrationView.as_view(), name='integrations'),
url(r'facebookinsightintegration', views.FacebookInsightsIntegrationView.as_view(), name='fbinsightintegrations'),
url(r'facebookadsintegration', views.FacebookAdsIntegrationView.as_view(), name='facebookadsintegration'),
url(r'analyticsintegration', views.GoogleAnalyticsIntegrationView.as_view(), name='analyticsintegration'),
url(r'pinterestintegration', views.PinterstIntegrationView.as_view(), name='pinterestintegration'),
url(r'five9tintegration', views.Five9IntegrationView.as_view(), name='five9tintegration'),
url(r'facebook/ads', views.FacebookAdAuthView.as_view(), name='facebookadsrcintegration'),
url(r'pages/insights', views.FacebookPageAuthView.as_view(), name='facebookinsightsrcintegration'),
url(r'google/analytics', views.GoogleAuthView.as_view(), name='analyticssrcintegration'),
url(r'pinterest/boards', views.PinterestAuthView.as_view(), name='pinterestsrcintegration'),
url(r'fiveNine', views.Five9AuthView.as_view(), name='five9srctintegration'),
url(r'five9details', views.FiveNineDetailView.as_view(), name='fiveNinedetails'),
url(r'fbaddetails', views.FBAdDetialsView.as_view(), name='fbaddetails'),
url(r'fbinsightdetails', views.FBInsightDetailView.as_view(), name='fbinsightdetails'),
url(r'googleanalyticsdetails', views.GoogleAnalyticsDetailView.as_view(), name='googleanalyticsdetails'),
url(r'pinterestdetails', views.PinterestDetailView.as_view(), name='pinterestdetails'),
url(r'datasourceset', views.DataSourceSetView.as_view(), name='get_data_source_set'),
url(r'datatarget', views.DataTargetView.as_view(), name='get_data_target'),
url(r'mysqltarget', views.MysqlTargetView.as_view(), name='mysqltarget'),
url(r'bigquerytarget', views.GoogleBigQueryAuthView.as_view(), name='bigquerytarget'),
url(r'googlebigquerydetails', views.GoogleBigQueryDetailView.as_view(), name='googlebigquerydetails'),
url(r'integrationsuccess', views.IntegrationSuccessView.as_view(), name='integration_success'),
url(r'testdbconnection', views.TestDbConnectionView.as_view(), name='testdbconnection'),
#
]

etlrobot/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('etl_robot_app.urls')),
url(r'^password_reset/$', auth_views.password_reset,{'template_name':'passwordreset/password_reset_form.html', 'html_email_template_name':'passwordreset/password_reset_email.html',
                   'subject_template_name':'passwordreset/password_reset_subject.txt'}, name='password_reset'),

url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm,{'template_name':'passwordreset/password_reset_confirm.html'}, name='password_reset_confirm'),

url(r'^password_reset/done/$', auth_views.password_reset_done,{'template_name':'passwordreset/password_reset_done.html'}, name='password_reset_done'),

url(r'^reset/done/$', auth_views.password_reset_complete,{'template_name':'passwordreset/password_reset_complete.html'}, name='password_reset_complete'),
url(r'^auth/', include('social_django.urls', namespace='social')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

etl_robot_app/forms.py
from django import forms
import re
from django.core.exceptions import ValidationError
from .models import User
class RegistrationForm(forms.Form):
    email =forms.EmailField(widget=forms.EmailInput(
        attrs={
        'class':'form-control',
        'id':'email',
        'onkeyup':"this.setAttribute('value', this.value);",
        'onblur' : "this.setAttribute('value', this.value);",
        'autocomplete':"off",
        #'required':'true'
        }
    ))
    first_name = forms.CharField(max_length=100,widget=forms.TextInput(
        attrs={
        'class':'form-control',
        'id':'fName',
        'onkeyup':"this.setAttribute('value', this.value);",
        'onblur' : "this.setAttribute('value', this.value);",
        'autocomplete':"off",
        #'required': 'true'
        }
    ))
    last_name =forms.CharField(max_length=200,widget=forms.TextInput(
        attrs={
        'class':'form-control',
        'id':'lName',
        'onkeyup':"this.setAttribute('value', this.value);",
        'onblur' : "this.setAttribute('value', this.value);",
        'autocomplete':"off"
        }
    ))
    company = forms.CharField(max_length=200, widget=forms.TextInput(
        attrs={
        'class':'form-control',
        'id':'Company',
        'onkeyup':"this.setAttribute('value', this.value);",
        'onblur' : "this.setAttribute('value', this.value);",
        'autocomplete':"off",
       # 'required':'true'
    }
    )  )

    # policy_accept = forms.BooleanField(widget=forms.CheckboxInput(
    #     attrs={
    #         'id':'useProxy',
    #         'data - parsley - multiple' : "useProxy",
    #
    # }
    # ))

    policy_accept = forms.BooleanField()



    def clean_email(self):
        email = self.cleaned_data.get('email')
        reg = re.compile('^[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$')

        if not reg.match(str(email)):
            raise ValidationError('Invalid Email')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError(u'Email "%s" is already in use.' % email)
        return self.cleaned_data.get('email')

    def clean_first_name(self):
        first_name = self.cleaned_data.get('first_name')

        reg = re.compile('^[a-zA-Z]*$')
        if not reg.match(str(first_name)):
            raise ValidationError('Invalid First Name')
        return self.cleaned_data.get('first_name')

    def clean_last_name(self):
        last_name = self.cleaned_data.get('last_name')

        reg = re.compile('^[a-zA-Z]*$')
        if not reg.match(str(last_name)):
            raise ValidationError('Invalid Last Name')
        return self.cleaned_data.get('last_name')

    def clean_company(self):
        company = self.cleaned_data.get('company')

        reg = re.compile('^[a-z0-9A-Z._]*$')
        if not reg.match(str(company)):
            raise ValidationError('Invalid Company')
        return self.cleaned_data.get('company')

    def clean_policy_accept(self):
        policy_accept = self.cleaned_data.get('policy_accept')
        if policy_accept == True:
            return self.cleaned_data.get('policy_accept')
        else:
            raise ValidationError('Accept Terms and Condition')





class FiveNineForm(forms.Form):
    email =forms.EmailField()
    password =forms.CharField(widget=forms.PasswordInput)

    def clean_password(self):
        password = self.cleaned_data.get('password')
        if password==None:
            raise ValidationError('Password Required')
        return self.cleaned_data.get('password')

    def clean_email(self):
        email = self.cleaned_data.get('email')
        reg = re.compile('^[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$')

        if not reg.match(str(email)):
            raise ValidationError('Invalid Email')
        return self.cleaned_data.get('email')


class MysqlForm(forms.Form):
    schema_name = forms.CharField()
    table_prefix = forms.CharField()
    host = forms.CharField()
    port = forms.CharField()
    user = forms.CharField()
    tar_password = forms.CharField(widget=forms.PasswordInput)
    enc_type = forms.CharField(widget=forms.Select)
    ssh_port = forms.CharField(required=False)
    ssh_user = forms.CharField(required=False)
    remote_address = forms.CharField(required=False)
    public_key = forms.CharField(required=False,widget=forms.Textarea)

    def clean_schema_name(self):
        schema_name = self.cleaned_data.get('schema_name')
        reg = re.compile('^[a-z0-9A-Z_ ]*$')
        if not reg.match(str(schema_name)):
            raise ValidationError('Invalid Schema')
        return self.cleaned_data.get('schema_name')

    def clean_table_prefix(self):
        table_prefix = self.cleaned_data.get('table_prefix')
        reg = re.compile('^[a-z0-9A-Z_ ]*$')
        if not reg.match(str(table_prefix)):
            raise ValidationError('Invalid Table Prefix')
        return self.cleaned_data.get('table_prefix')

    def clean_host(self):
        host = self.cleaned_data.get('host')
        reg = re.compile('^[a-z0-9A-Z_.-]*$')
        if not reg.match(str(host)):
            raise ValidationError('Invalid Host')
        if host=="localhost":
            raise ValidationError('localhost is not allowed')
        return self.cleaned_data.get('host')
    def clean_tar_password(self):
        password = self.cleaned_data.get('tar_password')
        if password == None:
            raise ValidationError('Password Required')
        return self.cleaned_data.get('tar_password')

    def clean_port(self):
        port = self.cleaned_data.get('port')
        reg = re.compile('^[0-9]*$')
        if not reg.match(str(port)):
            raise ValidationError('Invalid Port')
        return self.cleaned_data.get('port')

    def clean_user(self):
        user = self.cleaned_data.get('user')
        reg = re.compile('^[a-zA-Z_@.-]*$')
        if not reg.match(str(user)):
            raise ValidationError('Invalid User')
        return self.cleaned_data.get('user')

    # def clean(self):
    #     enc_type = self.cleaned_data.get('enc_type')
    #     ssh_port = self.cleaned_data.get('ssh_port')
    #     ssh_user = self.cleaned_data.get('ssh_user')
    #     reg_port = re.compile('^[0-9]*$')
    #     reg_user = re.compile('^[a-zA-Z_@.-]*$')
    #     print(enc_type,"xsfdsf")
    #     print(not reg_port.match(str(ssh_port)))
    #     if enc_type == "ssh_tunnel":
    #         if not reg_port.match(str(ssh_port))==False:
    #             raise ValidationError('Invalid Port')
    #         if not reg_user.match(str(ssh_user)) or ssh_user == None:
    #             raise ValidationError('Invalid User')
    #
    # def clean_ssh_port(self):
    #     enc_type = self.cleaned_data.get('enc_type')
    #     ssh_port = self.cleaned_data.get('ssh_port')
    #     reg = re.compile('^[0-9]*$')
    #     try:
    #         if enc_type == "ssh_tunnel":
    #             if not reg.match(str(ssh_port)) or ssh_port==None:
    #                 raise ValidationError('Invalid Port')
    #
    #     except:
    #         pass
    #     return ssh_port
    #
    # def clean_ssh_user(self):
    #     enc_type = self.cleaned_data.get('enc_type')
    #     ssh_user = self.cleaned_data.get('ssh_user')
    #     reg_user = re.compile('^[a-zA-Z_@.-]*$')
    #     try:
    #         if enc_type == "ssh_tunnel":
    #             if not reg.match(str(ssh_user))or ssh_user==None:
    #                 raise ValidationError('Invalid User')
    #     except:
    #         pass
    #     return ssh_user
    #
    # def clean_remote_address(self):
    #     enc_type = self.cleaned_data.get('enc_type')
    #     remote_address = self.cleaned_data.get('remote_address')
    #     reg = re.compile('^[0-9.:]*$')
    #     try:
    #         if enc_type == "ssh_tunnel":
    #             if not reg.match(str(remote_address)) or remote_address==None:
    #                 raise ValidationError('Invalid remote address')
    #     except:
    #         pass
    #     return remote_address
    #
    # def clean_public_key(self):
    #     enc_type = self.cleaned_data.get('enc_type')
    #     public_key = self.cleaned_data.get('public_key')
    #     try:
    #         if enc_type == "ssh_tunnel":
    #             if public_key==None:
    #                 raise ValidationError('Public Key Required')
    #     except:
    #         pass
    #     return public_key

etl_robot_app/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">

    <title>{% block title %}ETL Robot{% endblock %}</title>

    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css"> -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,500,300' rel='stylesheet' type='text/css'>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet"/>
      <link rel="stylesheet" href="{% static 'assets/css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">

  </head>
  <body>

   {% block content %}
   <footer>{% block footer %}<p>Copyright © 2018 <a class="link-d" href="javascript: void(0)">ETL Robot.</a> All rights reserved.</p>{% endblock %}</footer>
    {% endblock %}

{% block script %}
   {% endblock %}
<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" type="text/javascript"></script>
  <script type="text/javascript" src="{% static 'assets/js/bootstrap-notify.js' %}"></script>
  </body>
</html>

etl_robot_app/templates/dashboardbase.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">

    <title>{% block title %}Dashboard | etlrobotsaas{% endblock %}</title>

    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css"> -->
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"> -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,500,300' rel='stylesheet' type='text/css'>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet"/>
    <link rel="stylesheet" href="{% static 'assets/css/daterangepicker.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/jquery-customselect.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
          <style type="text/css">
      svg.m_loader{
          position: absolute;
          width: 100px;
          height: 152px;
          margin: 0px;
          display:inline-block;
          background: url({% static 'assets/img/etl-logo-loader.svg' %}) no-repeat center center;
          background-size: cover;
        }
        .svgLoaderCon{
          display: flex;
          top: 0;
          right: 0;
          bottom: 0;
          left: 0;
          background: rgba(255, 255, 255, 1);
          flex: 1;
          justify-content: center;
          align-items: center;
          position: absolute;
          z-index: 5000000;
        }
        .svgLoaderCon p{
          font-size: 13px;
          margin-top: 207px;
          color: #999;
        }
        .loaderOn{
          overflow: hidden;
        }
        .innerWrapper.loading{
          position: relative;
        }

        .elementsLoader{
          display: none;
          top: 0;
          right: 0;
          bottom: 0;
          left: 0;
          background: rgba(255, 255, 255, 1);
          flex: 1;
          justify-content: center;

          position: absolute;
          z-index: 1;
        }
        .loaderOnsvg.e_loader{
          width: 100px;
          height: 152px;
          margin: 0px;
          margin-top: 150px;
            display:inline-block;
        }

        .loaderCon .e_loader{
          width: 100px;
          height: 32px;
          margin: 0px;
          margin-top: 0px;
            display:inline-block;
        }

        .innerWrapper.loading .elementsLoader{
            display: flex;
        }

        .loaderCon.loading{
          position: relative;
        }

        .loaderCon .elementsLoader{
          display: none;
          top: 0;
          right: 0;
          bottom: 0;
          left: 0;
          background: rgba(255, 255, 255, 1);
          flex: 1;
          justify-content: center;
          align-items: center;
          position: absolute;
          z-index: 1;
        }
        .loaderCon.loading .elementsLoader{
            display: flex;
        }
    </style>


  </head>
  <body>

  <div class="mainCon">

      <nav class="leftNav">
        <ul class="leftUl">
          <li>
            <a class="brandLogo"><img class="" src="{% static 'assets/img/logo-ETLRobot.png' %}" alt=""></a>
          </li>
          <li class="leftNavLab">
            Navigation
          </li>
          <li class="active">
            <a href="{% url 'etl_robot_app:dashboard'%}">
              <span class="navIcon"><i class="fas fa-tachometer-alt"></i></span>
              <span class="navText">Dashboard</span>
            </a>
          </li>
          <li>
            <a href="{% url 'etl_robot_app:integrations' %}">
              <span class="navIcon"><i class="fas fa-address-book"></i></span>
              <span class="navText">Integrations</span>
            </a>
          </li>
          <li>
            <a href="javascript: void(0)">
              <span class="navIcon"><i class="fas fa-tasks"></i></span>
              <span class="navText">My Plans</span>
            </a>
          </li>
          <li>
            <a href="javascript: void(0)">
              <span class="navIcon"><i class="fas fa-envelope"></i></span>
              <span class="navText">Invite</span>
            </a>
          </li>
        </ul>
      </nav>

      <div class="mainCon_inner">
        <div class="mainCon_wrapper">

          <nav class="navbar navbar-expand-lg navbar-light bg-light navbar-default top_nav_con">
            <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example-2">
                        <i class="fa fa-bars"></i>
                    </button>
                    <a class="navbar-brand" href="#">{% block navtitle %}Dashboard{% endblock %}</a>

            </div>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">

              </ul>
              <ul class="nav navbar-user navbar-right">
                  <li class="nav-item">
                    <a class="nav-link nav_link_user" href="javascript: void(0);" id="dropdown03" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <span class="img nav_notifi_con">
                        <i class="far fa-envelope"></i>
                        <i class="noti_Count">0</i>
                      </span>
                    </a>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link nav_link_user" href="javascript: void(0);" id="dropdown03" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <span class="img">
                        <i class="far fa-user"></i>
                      </span>
                      <span class="name">
                        {{ user.first_name }} {{user.last_name}}
                        {{user.account.id}}
                      </span>
                      <span class="userDownAngle">
                        <i class="fas fa-angle-down"></i>
                      </span>
                    </a>
                    <div class="dropdown-menu userDropDown" aria-labelledby="dropdown03">
                      <a class="dropdown-item" href="#">My Account</a>
                      <a class="dropdown-item" href="#">Settings</a>
                      <a class="dropdown-item signOut" href="{% url 'etl_robot_app:logout' %}">Sign Out</a>
                    </div>
                  </li>
                </ul>
            </div>
          </nav>

          <!-- <nav class="navbar navbar-default navbar-fixed">
            <div class="container-fluid top_nav_con">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example-2">
                        <i class="fa fa-bars"></i>
                    </button>
                    <a class="navbar-brand" href="#">Dashboard</a>

                </div>
                <ul class="nav navbar-user navbar-right">
                  <li class="nav-item">
                    <a class="nav-link nav_link_user" href="javascript: void(0);" id="dropdown03" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <span class="img">
                        <i class="fa fa-envelope-o"></i>
                      </span>
                    </a>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link nav_link_user dropdown-toggle" href="javascript: void(0);" id="dropdown03" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <span class="img">
                        <i class="fa fa-user-o"></i>
                      </span>
                      <span class="name">
                        Username
                      </span>
                    </a>
                    <div class="dropdown-menu userDropDown" aria-labelledby="dropdown03">
                      <a class="dropdown-item" href="#">My Account</a>
                      <a class="dropdown-item" href="#">Settings</a>
                      <a class="dropdown-item signOut" href="#">Sign Out</a>
                    </div>
                  </li>
                </ul>
            </div>
        </nav> -->

          <div class="innerWrapper">
             <div class="elementsLoader">
              <svg class="e_loader" version="1.1" id="L4" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 100 100" enable-background="new 0 0 0 0" xml:space="preserve">
                <circle fill="#ddd" stroke="none" cx="6" cy="50" r="6">
                  <animate
                    attributeName="opacity"
                    dur="1s"
                    values="0;1;0"
                    repeatCount="indefinite"
                    begin="0.1"/>
                </circle>
                <circle fill="#ddd" stroke="none" cx="26" cy="50" r="6">
                  <animate
                    attributeName="opacity"
                    dur="1s"
                    values="0;1;0"
                    repeatCount="indefinite"
                    begin="0.2"/>
                </circle>
                <circle fill="#ddd" stroke="none" cx="46" cy="50" r="6">
                  <animate
                    attributeName="opacity"
                    dur="1s"
                    values="0;1;0"
                    repeatCount="indefinite"
                    begin="0.3"/>
                </circle>
              </svg>
            </div>

           {% block content %}
            {% endblock %}


          </div> <!-- .innerWrapper -->


        </div> <!-- .mainCon_wrapper -->

        <footer class="loginFooter">
          <p>Copyright © 2018 <a class="link-d" href="javascript: void(0)">ETL Robot.</a> All rights reserved.</p>
        </footer>

      </div>
    </div>
<div class="svgLoaderCon">
      <svg class="m_loader" version="1.1" id="L5" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
        viewBox="0 0 100 100" enable-background="new 0 0 0 0" xml:space="preserve">
        <circle fill="#08ac67" stroke="none" cx="40" cy="60" r="3">
          <animateTransform
             attributeName="transform"
             dur="1s"
             type="translate"
             values="0 15 ; 0 -15; 0 15"
             repeatCount="indefinite"
             begin="0.1"/>
        </circle>
        <circle fill="#08ac67" stroke="none" cx="50" cy="60" r="3">
          <animateTransform
             attributeName="transform"
             dur="1s"
             type="translate"
             values="0 10 ; 0 -10; 0 10"
             repeatCount="indefinite"
             begin="0.2"/>
        </circle>
        <circle fill="#08ac67" stroke="none" cx="60" cy="60" r="3">
          <animateTransform
             attributeName="transform"
             dur="1s"
             type="translate"
             values="0 5 ; 0 -5; 0 5"
             repeatCount="indefinite"
             begin="0.3"/>
        </circle>
      </svg>
      <p>Please wait ...</p>
    </div>


   <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script type="text/javascript" src="{% static 'assets/js/moment.js' %}"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" type="text/javascript"></script>
    <script type="text/javascript" src="{% static 'assets/js/daterangepicker.js' %}"></script>
    <script type="text/javascript" src="{% static 'assets/js/bootstrap-notify.js' %}"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.2.61/jspdf.min.js"></script>
     <script type="text/javascript" src="{% static 'assets/js/jquery-customselect.js' %}"></script>
    <script type="text/javascript">
    $('[data-toggle="tooltip"]').tooltip();

    $(window).on("load", function (e) {

      $('.svgLoaderCon').fadeOut();
      $('body').removeClass('loaderOn');

    });

    getNotificationCount()
    function getNotificationCount() {
    $('.innerWrapper').addClass('loading')
    $.post('{% url 'etl_robot_app:notification_count' %}', {
        csrfmiddlewaretoken: '{{ csrf_token }}',
      },
      function(data) {
      $('.innerWrapper').removeClass('loading')
        if (data.status) {
          if(data.data['notification']==0)
            {
            $('.notification_count,.noti_Count').html('0')
            $.notify({
          icon: 'fas fa-info-circle',
            message: "No <b>Notification</b> to show."

          },{
            type: 'info',
            timer: 2000
        });



            }
          else
            $('.notification_count,.noti_Count').html(data.data['notification'])
        }
        else
        {
         $.notify({
          icon: ' fas fa-times-circle',
            message: data.message

          },{
            type: 'danger',
            timer: 2000
        });

        }
      })

}
      {% block script %}

{% endblock %}
  </script>

  </body>
</html>